image: gradle:alpine

stages:
  - test
  - publish

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - build
    - .gradle



##############
#    JOBS    #
##############

build:
  stage: test
  script:
    - gradle assemble

test:
  stage: test
  script:
    - gradle jacocoTestReport coveralls

bintray:publish:
  stage: publish
  script:
    - ./gradlew bintrayUpload
  only:
    - tags
