image: gradle

stages:
  - test
  - publish

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle



##############
#    JOBS    #
##############

build:
  stage: test
  cache:
    paths:
      - build
      - .gradle
  script:
    - gradle assemble

#test:
#  stage: test
#  cache:
#    paths:
#      - build
#      - .gradle
#  script:
#    - gradle jacocoTestReport coveralls

bintray:publish:
  stage: publish
  cache:
    paths:
      - build
      - .gradle
  script:
    - ./gradlew bintrayUpload
  only:
    - tags

pages:
  image: node
  stage: publish
  artifacts:
    paths:
      - public
  before_script:
    - git submodule update --init
    - cd docs
    - cd themes/docsy
    - git submodule update --init
    - cd ../..
  script:
    - yarn
    - yarn build
  only:
    - master

