title: KGraphQL
description: >-
  Pure Kotlin GraphQL implementation
baseurl: "/kgraphql/"
url: "https://apurebase.gitlab.io"

# Build settings
markdown: kramdown
theme: "just-the-docs"

permalink: pretty


# Just the Docs
search_enabled: true
color_scheme: test
sass:
  load_paths:
    - _sass
aux_links:
  "KGraphQL on GitHub":
    - "//github.com/apurebase/kgraphql"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - any_additional_item # any user-specific listing goes at the end
