name: Deploy Docs
on:
  push:
    branches:
      - master


jobs:
  build:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }} 
          path: docs/
          repository: jeggy/kgraphql-docs
          tags: latest
